### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by GuMilano** [jerrodrs/DayZ-hack#1]
Can you help me?
how to run the code? I tried using vscode but I was not successful it gives an error
I try to run the dayz_toolkit.sln file but the error

Invalid expression term ")"

![Capturar](https://user-images.githubusercontent.com/76005264/177644634-7742a4e7-c865-465d-8f85-3fd3bc7f88ba.PNG)

**Comment by jerrodrs** [comment]
Sorry this project is long gone and dead :) best to use it as a reference at this point only.
